import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import astro from 'eslint-plugin-astro';
import globals from 'globals';
import prettier from 'eslint-config-prettier';

// ESLint 9 flat config. Type-aware linting is intentionally off (keeps it fast and
// config-free); `astro check` already provides full type checking across .astro and .ts.
// eslint-plugin-astro parses the .astro component frontmatter/template; eslint-config-prettier
// comes last to disable any stylistic rules that would fight Prettier.
export default tseslint.config(
  {
    ignores: [
      'dist',
      '.astro',
      'node_modules',
      'public',
      'pagefind',
      'src/env.d.ts', // generated by Astro (triple-slash refs are intentional)
      '.venv', // local Python/Quarto env — not part of the site
      '.paper-text', // scratch: extracted paper text for drafting
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  ...astro.configs.recommended,
  {
    // Site code runs in the browser (React islands, client scripts) and at build time (Node).
    languageOptions: {
      globals: { ...globals.browser, ...globals.node },
    },
  },
  {
    // TypeScript (and `astro check`) already resolve globals/types across .ts and .astro,
    // so core no-undef only produces false positives on type-only globals (e.g. ImageMetadata).
    files: ['**/*.ts', '**/*.tsx', '**/*.astro'],
    rules: { 'no-undef': 'off' },
  },
  prettier,
);
